// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCpOCgpTVE9ORV9UWVBFEhQKEFNUT05F",
            "X1RZUEVfQkxBTksQABIUChBTVE9ORV9UWVBFX0JMQUNLEAESFAoQU1RPTkVf",
            "VFlQRV9XSElURRACKlEKC1BMQVlFUl9UWVBFEhQKEFBMQVlFUl9UWVBFX05P",
            "TkUQABIVChFQTEFZRVJfVFlQRV9CTEFDSxABEhUKEVBMQVlFUl9UWVBFX1dI",
            "SVRFEAIqYwoMUExBWUVSX1NUQVRFEh0KGVBMQVlFUl9TVEFURV9ESVNDT05O",
            "RUNURUQQABIaChZQTEFZRVJfU1RBVEVfQ09OTkVDVEVEEAESGAoUUExBWUVS",
            "X1NUQVRFX1BMQVlJTkcQAipmCgxMT0dfSU5fRVJST1ISFQoRTE9HX0lOX0VS",
            "Uk9SX05PTkUQABIiCh5MT0dfSU5fRVJST1JfQUxSRUFEWV9DT05ORUNURUQQ",
            "ARIbChdMT0dfSU5fRVJST1JfTk9fQUNDT1VOVBACKmkKDVNJR05fVVBfRVJS",
            "T1ISFgoSU0lHTl9VUF9FUlJPUl9OT05FEAASIQodU0lHTl9VUF9FUlJPUl9B",
            "TFJFQURZX1NJR05fVVAQARIdChlTSUdOX1VQX0VSUk9SX1dST05HX0NPVU5U",
            "EAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.STONE_TYPE), typeof(global::Protocol.PLAYER_TYPE), typeof(global::Protocol.PLAYER_STATE), typeof(global::Protocol.LOG_IN_ERROR), typeof(global::Protocol.SIGN_UP_ERROR), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum STONE_TYPE {
    [pbr::OriginalName("STONE_TYPE_BLANK")] Blank = 0,
    [pbr::OriginalName("STONE_TYPE_BLACK")] Black = 1,
    [pbr::OriginalName("STONE_TYPE_WHITE")] White = 2,
  }

  public enum PLAYER_TYPE {
    [pbr::OriginalName("PLAYER_TYPE_NONE")] None = 0,
    [pbr::OriginalName("PLAYER_TYPE_BLACK")] Black = 1,
    [pbr::OriginalName("PLAYER_TYPE_WHITE")] White = 2,
  }

  public enum PLAYER_STATE {
    [pbr::OriginalName("PLAYER_STATE_DISCONNECTED")] Disconnected = 0,
    [pbr::OriginalName("PLAYER_STATE_CONNECTED")] Connected = 1,
    [pbr::OriginalName("PLAYER_STATE_PLAYING")] Playing = 2,
  }

  public enum LOG_IN_ERROR {
    [pbr::OriginalName("LOG_IN_ERROR_NONE")] None = 0,
    [pbr::OriginalName("LOG_IN_ERROR_ALREADY_CONNECTED")] AlreadyConnected = 1,
    [pbr::OriginalName("LOG_IN_ERROR_NO_ACCOUNT")] NoAccount = 2,
  }

  public enum SIGN_UP_ERROR {
    [pbr::OriginalName("SIGN_UP_ERROR_NONE")] None = 0,
    [pbr::OriginalName("SIGN_UP_ERROR_ALREADY_SIGN_UP")] AlreadySignUp = 1,
    [pbr::OriginalName("SIGN_UP_ERROR_WRONG_COUNT")] WrongCount = 2,
  }

  #endregion

}

#endregion Designer generated code
